# Generated by Django 5.0.3 on 2024-04-05 21:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caped',
            fields=[
                ('nome', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('periodo', models.CharField(choices=[('Primeiro', '1ª'), ('Segundo', '2ª'), ('Terceiro', '3ª'), ('Quarto', '4ª'), ('Quinto', '5ª'), ('Sexto', '6ª'), ('Sétimo', '7ª'), ('Oitavo', '8ª'), ('Nono', '9ª')], default='Primeiro', max_length=8)),
                ('turno', models.CharField(choices=[('Manhã', 'M'), ('Tarde', 'T'), ('Noite', 'N')], default='Manhã', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'CAPED',
            },
        ),
        migrations.CreateModel(
            name='discente',
            fields=[
                ('nome', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('periodo', models.CharField(choices=[('Primeiro', '1ª'), ('Segundo', '2ª'), ('Terceiro', '3ª'), ('Quarto', '4ª'), ('Quinto', '5ª'), ('Sexto', '6ª'), ('Sétimo', '7ª'), ('Oitavo', '8ª'), ('Nono', '9ª')], default='Primeiro', max_length=8)),
                ('turno', models.CharField(choices=[('Manhã', 'M'), ('Tarde', 'T'), ('Noite', 'N')], default='Manhã', max_length=10)),
            ],
            options={
                'verbose_name': 'Discente',
                'verbose_name_plural': 'Discentes',
            },
        ),
        migrations.CreateModel(
            name='folhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Folha',
                'verbose_name_plural': 'Folhas',
            },
        ),
        migrations.CreateModel(
            name='emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantidade', models.PositiveIntegerField(default=15)),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_discentes', to='cadastro.discente')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_responsaveis', to='cadastro.caped')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
