# Generated by Django 5.0.4 on 2024-04-13 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='folhas',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='caped',
        ),
    ]
