# Generated by Django 5.0.4 on 2024-04-14 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_meumodelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeuModelo',
        ),
    ]
