# Generated by Django 5.0.4 on 2024-04-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_delete_meumodelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='responsavel',
        ),
    ]
