# Generated by Django 5.0.4 on 2024-04-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_remove_emprestimo_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='para_excluir',
            field=models.BooleanField(default=False),
        ),
    ]
