# Generated by Django 5.0.4 on 2024-04-14 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_emprestimo_para_excluir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='para_excluir',
        ),
        migrations.CreateModel(
            name='planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamento_discentes', to='cadastro.discente')),
            ],
        ),
    ]
