# Generated by Django 5.0.4 on 2024-04-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_remove_emprestimo_para_excluir_planejamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='planejamento',
        ),
    ]
